<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.softwareloop.uploaderplus</groupId>
    <artifactId>uploader-plus</artifactId>
    <version>1.9-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>uploader-plus</name>
    <description>An Alfresco uploader that prompts for metadata</description>
    <url>https://github.com/softwareloop/uploader-plus</url>

    <prerequisites>
        <maven>3.3.0</maven>
    </prerequisites>

    <licenses>
        <license>
            <name>GNU LESSER GENERAL PUBLIC LICENSE, Version 3</name>
            <url>http://www.gnu.org/licenses/lgpl.html</url>
            <distribution>repo</distribution>
            <comments>OSI-approved license</comments>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git@github.com:softwareloop/uploader-plus.git</connection>
        <developerConnection>scm:git:git@github.com:softwareloop/uploader-plus.git</developerConnection>
        <url>git@github.com:softwareloop/uploader-plus.git</url>
      <tag>HEAD</tag>
  </scm>

    <developers>
        <developer>
            <name>Paolo Predonzani</name>
            <email>paolo.predonzani@gmail.com</email>
            <url>https://github.com/softwareloop</url>
        </developer>
        <developer>
            <name>Douglas C. R. Paes</name>
            <url>https://github.com/douglascrp</url>
        </developer>
        <developer>
            <name>Younes Regaieg</name>
            <url>https://github.com/yregaieg</url>
        </developer>
    </developers>

    <contributors>
        <contributor>
            <name>Axel Faust</name>
            <url>https://github.com/AFaust</url>
        </contributor>
        <contributor>
            <name>Stéphane Prouvez</name>
            <url>https://github.com/sprouvez</url>
        </contributor>
        <contributor>
            <name>Oksana Kurysheva</name>
            <url>https://github.com/aviriel</url>
        </contributor>
        <contributor>
            <name>Magnus Pedersen</name>
            <url>https://github.com/magp3</url>
        </contributor>
        <contributor>
            <name>Alexander Mahabir</name>
            <url>https://github.com/alex4u2nv</url>
        </contributor>
        <contributor>
            <name>Roxana Angheluta</name>
            <url>https://github.com/anghelutar</url>
        </contributor>
        <contributor>
            <name>tomasrgar</name>
            <url>https://github.com/tomasrgar</url>
        </contributor>
        <contributor>
            <name>Tom Vandepoele</name>
            <url>https://github.com/tom-vandepoele</url>
        </contributor>
    </contributors>

    <!-- The parent section from HEAD was removed as the incoming branch implies a direct SDK setup with explicit properties. -->

    <properties>
        <!-- Alfresco SDK 4.5 related properties from incoming branch -->
        <alfresco.sdk.version>4.5.0</alfresco.sdk.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <alfresco.groupId>org.alfresco</alfresco.groupId>
        <alfresco.bomDependencyArtifactId>acs-community-packaging</alfresco.bomDependencyArtifactId>
        <alfresco.platform.version>7.3.0</alfresco.platform.version>
        <alfresco.platform.docker.user>alfresco</alfresco.platform.docker.user>
        <alfresco.share.version>17.137</alfresco.share.version>
        <alfresco.share.docker.version>7.3.0</alfresco.share.docker.version>
        <docker.acs.image>alfresco/alfresco-content-repository-community</docker.acs.image>
        <docker.share.image>alfresco/alfresco-share</docker.share.image>
        <keystore.settings>-Dencryption.keystore.type=JCEKS -Dencryption.cipherAlgorithm=AES/CBC/PKCS5Padding -Dencryption.keyAlgorithm=AES -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore -Dmetadata-keystore.password=mp6yc0UD9e -Dmetadata-keystore.aliases=metadata -Dmetadata-keystore.metadata.password=oKIWzVdEdA -Dmetadata-keystore.metadata.algorithm=AES</keystore.settings>
        <jrebel.version>1.1.8</jrebel.version>
        <share.port>8180</share.port>
        <share.debug.port>9898</share.debug.port>
        <acs.host>uploader-plus-acs</acs.host>
        <acs.port>8080</acs.port>
        <acs.debug.port>8888</acs.debug.port>
        <postgres.port>5555</postgres.port>
        <test.acs.endpoint.path/>
        <!-- Log4j2 version property from HEAD branch -->
        <alfresco74.log4j2.version>2.19.0</alfresco74.log4j2.version>
    </properties>

    <!-- Libs used in Unit and Integration tests from incoming branch -->
    <!-- IMPORTANT - Test dependencies need to be here in the top parent POM as
                     the Alfresco Maven IT Mojo runs as part of the parent project ... -->
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>4.2.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- The main Alfresco Repo dependency for compiling Java code in src/main/java -->
        <dependency>
            <groupId>${alfresco.groupId}</groupId>
            <artifactId>alfresco-remote-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- Bring in Alfresco RAD so we get access to AlfrescoTestRunner classes -->
        <dependency>
            <groupId>org.alfresco.maven</groupId>
            <artifactId>alfresco-rad</artifactId>
            <version>${alfresco.sdk.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <!-- This will import the dependencyManagement for all artifacts in the selected Alfresco platform.
                 NOTE: You still need to define dependencies in your POM, but you can omit version as
                       it's enforced by this dependencyManagement.
                 NOTE: It defaults to the latest version this SDK pom has been tested with,
                       but alfresco version can/should be overridden in your project's pom
            -->
            <dependency>
                <groupId>${alfresco.groupId}</groupId>
                <artifactId>${alfresco.bomDependencyArtifactId}</artifactId>
                <version>${alfresco.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Redefine the following Share dependencies as they have different version numbers than platform.
                 They are defined in alfresco-platform-distribution... -->
            <dependency>
                <groupId>${alfresco.groupId}</groupId>
                <artifactId>share</artifactId>
                <version>${alfresco.share.version}</version>
                <type>war</type>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>${alfresco.groupId}</groupId>
                <artifactId>share</artifactId>
                <version>${alfresco.share.version}</version>
                <classifier>classes</classifier>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>${alfresco.groupId}</groupId>
                <artifactId>alfresco-web-framework-commons</artifactId>
                <version>${alfresco.share.version}</version>
                <classifier>classes</classifier>
                <scope>provided</scope>
            </dependency>
            <!-- Log4j2 dependency from HEAD branch -->
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>${alfresco74.log4j2.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- To make a release:
         Make sure .m2/settings.xml is set up correctly according to:
         http://central.sonatype.org/pages/apache-maven.html
         mvn release:prepare -DdryRun=true
         Check everything and, if needed: mvn release:clean
         mvn release:prepare
         mvn release:perform
    -->
    <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>

    <build>
        <pluginManagement>
            <plugins>
                <!--
                    Build an AMP if 3rd party libs are needed by the extensions
                    JARs are the default artifact produced in your modules, if you want to build an amp for each module
                    you have to enable this plugin and inspect the src/main/assembly.xml file if you want to customize
                    the layout of your AMP. The end result is that Maven will produce both a JAR file and an AMP with your
                    module.
                -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>2.6</version>
                    <executions>
                        <execution>
                            <id>build-amp-file</id>
                            <phase>package</phase>
                            <goals>
                                <goal>single</goal>
                            </goals>
                            <configuration>
                                <appendAssemblyId>false</appendAssemblyId>
                                <descriptor>src/main/assembly/amp.xml</descriptor>
                            </configuration>
                        </execution>
                    </executions>
                    <dependencies>
                        <dependency>
                            <groupId>org.alfresco.maven.plugin</groupId>
                            <artifactId>alfresco-maven-plugin</artifactId>
                            <version>${alfresco.sdk.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
                
				<!-- Filter resources in any sub-project with this config -->
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.1.0</version>
					<configuration>
						<encoding>UTF-8</encoding>
						<nonFilteredFileExtensions>
							<!-- jpg, jpeg, gif, bmp and png are added automatically -->
							<nonFilteredFileExtension>ftl</nonFilteredFileExtension>
							<nonFilteredFileExtension>acp</nonFilteredFileExtension>
							<nonFilteredFileExtension>svg</nonFilteredFileExtension>
							<nonFilteredFileExtension>pdf</nonFilteredFileExtension>
							<nonFilteredFileExtension>doc</nonFilteredFileExtension>
							<nonFilteredFileExtension>docx</nonFilteredFileExtension>
							<nonFilteredFileExtension>xls</nonFilteredFileExtension>
							<nonFilteredFileExtension>xlsx</nonFilteredFileExtension>
							<nonFilteredFileExtension>ppt</nonFilteredFileExtension>
							<nonFilteredFileExtension>pptx</nonFilteredFileExtension>
							<nonFilteredFileExtension>bin</nonFilteredFileExtension>
							<nonFilteredFileExtension>lic</nonFilteredFileExtension>
							<nonFilteredFileExtension>swf</nonFilteredFileExtension>
							<nonFilteredFileExtension>zip</nonFilteredFileExtension>
							<nonFilteredFileExtension>msg</nonFilteredFileExtension>
							<nonFilteredFileExtension>jar</nonFilteredFileExtension>
							<nonFilteredFileExtension>ttf</nonFilteredFileExtension>
							<nonFilteredFileExtension>eot</nonFilteredFileExtension>
							<nonFilteredFileExtension>woff</nonFilteredFileExtension>
							<nonFilteredFileExtension>woff2</nonFilteredFileExtension>
							<nonFilteredFileExtension>css</nonFilteredFileExtension>
							<nonFilteredFileExtension>ico</nonFilteredFileExtension>
							<nonFilteredFileExtension>psd</nonFilteredFileExtension>
							<nonFilteredFileExtension>js</nonFilteredFileExtension>
						</nonFilteredFileExtensions>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.zeroturnaround</groupId>
					<artifactId>jrebel-maven-plugin</artifactId>
					<version>${jrebel.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.1.0</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>3.0.0-M1</version>
					<executions>
						<execution>
							<id>integration-test</id>
							<phase>integration-test</phase>
							<goals>
								<goal>integration-test</goal>
							</goals>
						</execution>
						<execution>
							<id>verify-test</id>
							<phase>verify</phase>
							<goals>
								<goal>verify</goal>
							</goals>
						</execution>
					</executions>
					<dependencies>
						<dependency>
							<groupId>org.apache.maven.surefire</groupId>
							<artifactId>surefire-junit47</artifactId>
							<version>3.0.0-M1</version>
						</dependency>
					</dependencies>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-dependency-plugin</artifactId>
					<version>3.1.1</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<!-- Make sure resources in sub-projects are filtered -->
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.7</version>
				<configuration>
					<encoding>UTF-8</encoding>
					<nonFilteredFileExtensions>
						<nonFilteredFileExtension>ftl</nonFilteredFileExtension>
						<nonFilteredFileExtension>acp</nonFilteredFileExtension>
						<nonFilteredFileExtension>jpg</nonFilteredFileExtension>
						<nonFilteredFileExtension>png</nonFilteredFileExtension>
						<nonFilteredFileExtension>gif</nonFilteredFileExtension>
						<nonFilteredFileExtension>pdf</nonFilteredFileExtension>
						<nonFilteredFileExtension>doc</nonFilteredFileExtension>
						<nonFilteredFileExtension>xls</nonFilteredFileExtension>
						<nonFilteredFileExtension>ppt</nonFilteredFileExtension>
						<nonFilteredFileExtension>bin</nonFilteredFileExtension>
						<nonFilteredFileExtension>lic</nonFilteredFileExtension>
						<nonFilteredFileExtension>swf</nonFilteredFileExtension>
					</nonFilteredFileExtensions>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>1.2</version>
				<executions>
					<execution>
						<id>enforce-maven</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireMavenVersion>
									<version>(,2.1.0),(2.1.0,2.2.0),(2.2.0,)</version>
									<message>Maven 2.1.0 and 2.2.0 produce incorrect GPG signatures and checksums respectively.</message>
								</requireMavenVersion>
							</rules>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- Filter the test resource files in the AIO parent project, and do property substitutions.
                 We need this config so this is done before the Alfresco Maven Plugin 'run' is executed. -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<inherited>false</inherited>
				<!-- Run only for the AIO parent Project -->
				<executions>
					<execution>
						<id>copy-and-filter-docker-resources</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.outputDirectory}/docker</outputDirectory>
							<resources>
								<resource>
									<directory>docker</directory>
									<filtering>true</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- Compress JavaScript files and store as *-min.js -->
			<plugin>
				<groupId>net.alchim31.maven</groupId>
				<artifactId>yuicompressor-maven-plugin</artifactId>
				<version>1.5.1</version>
				<executions>
					<!-- Compress the JS files under the assembly folder -->
					<execution>
						<id>compress-assembly</id>
						<goals>
							<goal>compress</goal>
						</goals>
						<configuration>
							<sourceDirectory>${project.basedir}/src/main/assembly/web</sourceDirectory>
							<outputDirectory>${project.basedir}/src/main/assembly/web</outputDirectory>
							<excludes>
								<exclude>**/webscripts/**</exclude>
								<exclude>**/site-webscripts/**</exclude>
								<exclude>**/META-INF/**</exclude>
								<exclude>**/*.lib.js</exclude>
								<exclude>**/*.css</exclude>
								<exclude>**/*-min.js</exclude>
								<exclude>**/*-min.css</exclude>
							</excludes>
							<force>true</force>
							<jswarn>false</jswarn>
						</configuration>
					</execution>
					<!-- Compress the JS files under the resources folder -->
					<execution>
						<id>compress-resources</id>
						<goals>
							<goal>compress</goal>
						</goals>
						<configuration>
							<excludes>
								<exclude>**/webscripts/**</exclude>
								<exclude>**/site-webscripts/**</exclude>
								<exclude>**/*.lib.js</exclude>
								<exclude>**/*.css</exclude>
								<exclude>**/*-min.js</exclude>
								<exclude>**/*-min.css</exclude>
							</excludes>
							<force>true</force>
							<jswarn>false</jswarn>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- Hot reloading with JRebel -->
			<plugin>
				<groupId>org.zeroturnaround</groupId>
				<artifactId>jrebel-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>generate-rebel-xml</id>
						<phase>process-resources</phase>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<!-- For more information about how to configure JRebel plugin see:
                         http://manuals.zeroturnaround.com/jrebel/standalone/maven.html#maven-rebel-xml -->
					<classpath>
						<fallback>all</fallback>
						<resources>
							<resource>
								<directory>${project.build.outputDirectory}</directory>
								<directory>${project.build.testOutputDirectory}</directory>
							</resource>
						</resources>
					</classpath>
					<!--
                      alwaysGenerate - default is false
                      If 'false' - rebel.xml is generated if timestamps of pom.xml and the current rebel.xml file are not equal.
                      If 'true' - rebel.xml will always be generated
                    -->
					<alwaysGenerate>true</alwaysGenerate>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>java8</id>
			<activation>
				<jdk>[1.8,11.0)</jdk>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>3.8.0</version>
						<configuration>
							<source>1.8</source>
							<target>1.8</target>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>java11</id>
			<activation>
				<jdk>[11.0,17)</jdk>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>3.8.0</version>
						<configuration>
							<release>11</release>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>java17</id>
			<activation>
				<jdk>[17,)</jdk>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>3.8.0</version>
						<configuration>
							<release>17</release>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	<!--
        Alfresco Maven Repositories
        -->
	<repositories>
		<repository>
			<id>alfresco-public</id>
			<url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
		</repository>
		<repository>
			<id>alfresco-public-snapshots</id>
			<url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>daily</updatePolicy>
			</snapshots>
		</repository>
		<!-- Alfresco Enterprise Edition Artifacts, put username/pwd for server in settings.xml -->
		<repository>
			<id>alfresco-private-repository</id>
			<url>https://artifacts.alfresco.com/nexus/content/groups/private</url>
		</repository>
		<repository>
			<id>alfresco-internal</id>
			<url>https://artifacts.alfresco.com/nexus/content/groups/internal</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>alfresco-plugin-public</id>
			<url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
		</pluginRepository>
		<pluginRepository>
			<id>alfresco-plugin-public-snapshots</id>
			<url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>daily</updatePolicy>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
	<modules>
		<module>uploader-plus-platform</module>
		<module>uploader-plus-share</module>
		<module>uploader-plus-platform-docker</module>
		<module>uploader-plus-share-docker</module>
	</modules>
</project>
